version: '3.8'

services:
  minio-server:
    image: quay.io/minio/minio
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpass
    command: server /data --console-address ":9001"